### ISSUE TITLE
这个项目没更新了，我这边写了一个二开的项目，优化了一些东西

### ISSUE THREAD

**Issue by r3x5ur** [system-cpu/wxappUnpacker#4]
[https://github.com/r3x5ur/unpack-wxapkg](https://github.com/r3x5ur/unpack-wxapkg)

**Comment by Kevin-free** [comment]
> https://github.com/r3x5ur/unpack-wxapkg

@r3x5ur 404了，请问有可访问地址吗？我现在遇到wxss丢失，请问你知道如何解决吗？
